# Matthew Conner - Week 5 Homework

### 1. What does Pandas stand for?
- Pandas stands for either Panel Data or Python Data Analysis.

### 2. What are the 2 collections used in Pandas?
- Rows and columns

### 3. Name 4 things Pandas can do for us.
- load
- manipulate
- prepare
- model

### 4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
- "Values"

### 5. What is a CSV?
- A comma separated value

### 6. When cleaning data what values do we not like in our data?
- 

In [27]:
#7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np

testArray = np.array(
                            [  
                                [ [1, 2], [3, 4], [5, 6]],
                                [ [7, 8], [9, 10], [11, 12]], 
                            ]
                        )
print("This is my 3D Array...\n", testArray)

reshapeArray = testArray.reshape(4,-1)
print("\nThis is my reshaped Array...\n", reshapeArray)

This is my 3D Array...
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

This is my reshaped Array...
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
#8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20.

import numpy as np

linearly = np.linspace(0, 20, num=6)
print("These are my linearly spaced values...", linearly)


#9. Make a Deep Copy of the above array.

twinArray = linearly.copy()
print("This is my Deep Copy...", twinArray)


These are my linearly spaced values... [ 0.  4.  8. 12. 16. 20.]
This is my Deep Copy... [ 0.  4.  8. 12. 16. 20.]


In [12]:
#10. Concatenate these 3 arrays into a new array named 'newArray'...
#    ([[25, 16]])
#    ([[11, 2], [13, 4]])
#    ([[7, 81], [5, 6], [11, 12]])

import numpy as np

arrayA = np.array([[25, 16]])
arrayB = np.array([[11, 2], [13, 4]])
arrayC = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arrayA, arrayB, arrayC), axis=0)
print("This is my array concatenation...\n", newArray)


#11. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print("\nThis is my sorted array...\n", np.sort(sortedArray))



This is my array concatenation...
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

This is my sorted array...
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [31]:
#12. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

import numpy as np
print(reshapeArray)

huey, duey, luey, donald = reshapeArray
print("\nhuey = ", huey)
print("duey = ", duey)
print("luey = ", luey)
print("donald = ", donald)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

huey =  [1 2 3]
duey =  [4 5 6]
luey =  [7 8 9]
donald =  [10 11 12]


In [ ]:
#13. Combined and sort the following arrays into one called 'comboArray'...
#    one = ([10, 11, 12, 13, 14, 15, 16, 17])
#    two = ([20, 21, 22, 23, 24, 25, 26, 27])
#    three = ([ 0, 1, 2, 3, 4, 5, 6, 7])